const express = require("express");
const dotenv = require("dotenv");
const cors = require("cors");
const connectDB = require("./config/db");
dotenv.config();
const path = require("path");
connectDB();
const app = express();
app.use(cors());
app.use(express.json());
// app.use("/api/products", require("./routes/productRoutes"));
app.use("/api", require("./routes/userRoutes"));
app.use("/api/payment", require("./routes/payment"));
app.use("/api", require("./routes/orderRoutes"));
app.use("/api", require("./routes/productRoutes"));
app.use("/api", require("./routes/upload"));
app.use("/upload", express.static(path.join(__dirname, "uploads")));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
